<h2 id="Pembobotan-dan-Similarity"><strong>Preprocessing</strong></h2>

In [79]:
import nltk
import string
import re
import pandas as pd
import os
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.stem import SnowballStemmer
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from string import punctuation
from autocorrect import spell

snowball_stemmer = SnowballStemmer('english')
wordnet_lemmatizer = WordNetLemmatizer()

In [80]:
data = pd.read_csv(os.path.join("requirement.csv"))
df = data

In [81]:
df['req'].tail(5)

149    Fixed up the formatting and table of contents,...
150    The diagram designer is in charge of designing...
151    Ways to avoid scope creep are to develop chang...
152    Be careful of “scope creep” which are uncontro...
153    The major technology that you rely upon could ...
Name: req, dtype: object

In [82]:
def autospell(text):
    spells = [spell(w) for w in (nltk.word_tokenize(text))]
    return " ".join(spells)

def to_lower(text):
    return text.str.lower()

def remove_numbers(text):
    output = ''.join(c for c in text if not c.isdigit())
    return output

def remove_punct(text):
    return ''.join(c for c in text if c not in punctuation)

def remove_Tags(text):
    cleaned_text = re.sub('<[^<]+?>', '', text)
    return cleaned_text

def sentence_tokenize(text):
    sent_list = []
    for w in nltk.sent_tokenize(text):
        sent_list.append(w)
    return sent_list

def word_tokenize(text):
    return [w for sent in nltk.sent_tokenize(text) for w in nltk.word_tokenize(sent)]

def remove_stopwords(sentence):
    stop_words = stopwords.words('english')
    return ' '.join([w for w in nltk.word_tokenize(sentence) if not w in stop_words])

def stem(text):
    stemmed_word = [snowball_stemmer.stem(word) for sent in nltk.sent_tokenize(text)for word in nltk.word_tokenize(sent)]
    return " ".join(stemmed_word)

def lemmatize(text):
    lemmatized_word = [wordnet_lemmatizer.lemmatize(word)for sent in nltk.sent_tokenize(text)for word in nltk.word_tokenize(sent)]
    return " ".join(lemmatized_word)        

In [83]:
lower_text = to_lower(df['req'])
word_list=[]
for i in lower_text:
    i = remove_numbers(i)
    i = remove_punct(i)
    i = remove_Tags(i)
    i = remove_stopwords(i)
    i = lemmatize(i)    
#     i = word_tokenize(i)
    word_list.append(i)

In [84]:
word_list

['user submit job associate deadline cost execution time',
 'user query cluster establish cost unit time submit job',
 'user monitor status submit job',
 'user cancel job submit',
 'user check credit balance',
 'user check usage history',
 'user check status node cluster',
 'user check usage pattern history cluster',
 'user check status submit job',
 'user check load node cluster',
 'user alters cost structure cluster',
 'user alters schedule policy cluster',
 'user take photo new student',
 'development process follow rational unified process rup approach',
 'sdms developed waterfall process model',
 'objective project develop meeting scheduler product organized routine allows u concentrate core element different phase easily efficiently',
 'web tier deal presentation logic page rendering',
 'eis tier responsible storing user profile ride advertisement',
 'runtime pattern applied',
 'development done extra application server',
 'application deployed application server working cluster 

In [71]:
dataprepp=pd.DataFrame(word_list)
dataprepp.to_csv('dataprep1.csv', index=False)

In [72]:
dataprepp.tail(5)

0
149  fixed formatting table content added template ...
150  diagram designer charge designing diagram proj...
151  way avoid scope creep develop change control p...
152  careful “ scope creep ” uncontrolled change la...
153  major technology rely upon could possibly fail...

<h2>TextRank Sentence (ga dipake)</h2>

In [86]:
def senetence_information(lemmatized_word):
  sent_info=[]
  for i,sent in enumerate(lemmatized_word):
    words=word_tokenize(sent)
    sent_dict={"sent_id":i,"sent_word_count":len(words)}
    sent_info.append(sent_dict)
    
  return sent_info

sent_info = senetence_information(word_list)
# news = pd.read_csv('dataprep1.csv', sep=',', encoding='latin-1')
# sent_info=[]
# for i in range(len(data)):
#     news['0'][i]=senetence_information(news['0'][i])
#     sent_info.append(news['0'][i])

In [87]:
def frequency_of_words(lemmatized_word):
  freq_info=[]
  for i,sent in enumerate(lemmatized_word):
    words=word_tokenize(sent)
    frequency_dict={}
    for word in words:
      if word in frequency_dict.keys():
        frequency_dict[word]=frequency_dict[word]+1
      else:
        frequency_dict[word]=1
    temp={"sent_id":i,"frequency_of_word":frequency_dict}
    freq_info.append(temp)
    
  return freq_info

freq_info = frequency_of_words(word_list)
# news = pd.read_csv('dataprep1.csv', sep=',', encoding='latin-1')
# freq_info=[]
# for i in range(len(data)):
#     news['0'][i]=frequency_of_words(news['0'][i])
#     freq_info.append(news['0'][i])

In [88]:
def unik_word(lemmatized_word):
  unik=[]
  for sents in lemmatized_word:
    for word in word_tokenize(sents):
      if word not in unik:
        unik.append(word)
  return unik

unik_words=unik_word(word_list)
# news = pd.read_csv('dataprep1.csv', sep=',', encoding='latin-1')
# unik_words=[]
# for i in range(len(data)):
#     news['0'][i]=unik_word(news['0'][i])
#     unik_words.append(news['0'][i])

In [89]:
unik_words

['user',
 'submit',
 'job',
 'associate',
 'deadline',
 'cost',
 'execution',
 'time',
 'query',
 'cluster',
 'establish',
 'unit',
 'monitor',
 'status',
 'cancel',
 'check',
 'credit',
 'balance',
 'usage',
 'history',
 'node',
 'pattern',
 'load',
 'alters',
 'structure',
 'schedule',
 'policy',
 'take',
 'photo',
 'new',
 'student',
 'development',
 'process',
 'follow',
 'rational',
 'unified',
 'rup',
 'approach',
 'sdms',
 'developed',
 'waterfall',
 'model',
 'objective',
 'project',
 'develop',
 'meeting',
 'scheduler',
 'product',
 'organized',
 'routine',
 'allows',
 'u',
 'concentrate',
 'core',
 'element',
 'different',
 'phase',
 'easily',
 'efficiently',
 'web',
 'tier',
 'deal',
 'presentation',
 'logic',
 'page',
 'rendering',
 'eis',
 'responsible',
 'storing',
 'profile',
 'ride',
 'advertisement',
 'runtime',
 'applied',
 'done',
 'extra',
 'application',
 'server',
 'deployed',
 'working',
 'future',
 'ibm',
 'running',
 'jboss',
 'database',
 'mysql',
 'redundancy

In [90]:
import numpy as np
def tf_calculation(sent_info,freq_info):
  tf_values=np.zeros(shape=(len(sent_info),len(unik_words)))
  for i,freq_info_dict in enumerate(freq_info):
    for word in freq_info_dict["frequency_of_word"].keys():
      tf=freq_info_dict["frequency_of_word"][word]/sent_info[i]["sent_word_count"]
      tf_values[i][unik_words.index(word)]=tf
  return tf_values
  
tf_values=tf_calculation(sent_info,freq_info)
print(tf_values)

[[0.125      0.125      0.125      ... 0.         0.         0.        ]
 [0.11111111 0.11111111 0.11111111 ... 0.         0.         0.        ]
 [0.2        0.2        0.2        ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.05263158 0.05263158 0.05263158]]


In [91]:
import math

def idf_calculate(sent_info,freq_info):
  idf_values=np.zeros(shape=(len(sent_info),len(unik_words)))
  for i,freq_info_dict in enumerate(freq_info):
    for word in freq_info_dict["frequency_of_word"].keys():
      sum=0
      for word_in_dict in freq_info:
        if word in set(word_in_dict["frequency_of_word"].keys()):
          sum=sum+word_in_dict["frequency_of_word"][word]
      idf_values[i][unik_words.index(word)]=math.log(len(word_list)/sum)
  return idf_values
        
idf_values=idf_calculate(sent_info,freq_info)
print(idf_values)

[[1.5712167  3.42751469 3.42751469 ... 0.         0.         0.        ]
 [1.5712167  3.42751469 3.42751469 ... 0.         0.         0.        ]
 [1.5712167  3.42751469 3.42751469 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 5.0369526  5.0369526  5.0369526 ]]


In [96]:
def tfidf_calculation(tf_values,idf_values):
  tfidf_values=np.zeros(shape=(len(sent_info),len(unik_words)))
  tfidf_values=np.multiply(tf_values,idf_values)
  return tfidf_values
for i in range(len(unik_words)):
    print(unik_words[i])
    tfidf_values=tfidf_calculation(tf_values,idf_values)
    print(tfidf_values)

user
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0.38083497 ... 0.         0.         0.        ]
 [0.31424334 0.68550294 0.68550294 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26510277 0.26510277 0.26510277]]
submit
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0.38083497 ... 0.         0.         0.        ]
 [0.31424334 0.68550294 0.68550294 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26510277 0.26510277 0.26510277]]
job
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497

[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0.38083497 ... 0.         0.         0.        ]
 [0.31424334 0.68550294 0.68550294 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26510277 0.26510277 0.26510277]]
phrased
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0.38083497 ... 0.         0.         0.        ]
 [0.31424334 0.68550294 0.68550294 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26510277 0.26510277 0.26510277]]
urcar
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0

[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0.38083497 ... 0.         0.         0.        ]
 [0.31424334 0.68550294 0.68550294 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26510277 0.26510277 0.26510277]]
material
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.38083497 0.38083497 ... 0.         0.         0.        ]
 [0.31424334 0.68550294 0.68550294 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.26510277 0.26510277 0.26510277]]
quickly
[[0.19640209 0.42843934 0.42843934 ... 0.         0.         0.        ]
 [0.17457963 0.3808349

In [49]:
def cosine_similarity(sent_1,sent_2):
  s1_dot_s2=np.sum(np.multiply(sent_1,sent_2))
  magnitude_of_s1=math.sqrt(np.sum(np.multiply(sent_1,sent_1)))
  magnitude_of_s2=math.sqrt(np.sum(np.multiply(sent_2,sent_2)))
  return s1_dot_s2/(magnitude_of_s1*magnitude_of_s2)

def cosine_matrix(tfidf_values):
  cosine_similarity_matrix=np.zeros(shape=(len(word_list),len(word_list)))
  for i in range(len(tfidf_values)):
    for j in range(len(tfidf_values)):
      cosine_similarity_matrix[i][j]=cosine_similarity(tfidf_values[i],tfidf_values[j])
  #normalize the matrix
  for idx in range(len(cosine_similarity_matrix)):
    cosine_similarity_matrix[idx] /= cosine_similarity_matrix[idx].sum()
    
  return cosine_similarity_matrix

cosine_similarity_matrix=cosine_matrix(tfidf_values)
print(cosine_similarity_matrix)

[[0.26813961 0.11054764 0.0886777  ... 0.         0.01486438 0.        ]
 [0.07434361 0.18032467 0.06647272 ... 0.         0.01114233 0.        ]
 [0.06953858 0.07751052 0.21026761 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.33367542 0.04942722 0.01224703]
 [0.01778746 0.01982662 0.         ... 0.04753023 0.32086918 0.        ]
 [0.         0.         0.         ... 0.0207332  0.         0.56488478]]


In [57]:
def text_rank(cosine_matrix,eps=0.0001,d=0.85):
  teleportation_factor=np.ones(len(word_list))/len(word_list)
  i=0
  while i<100:
    new_p=np.dot(cosine_similarity_matrix.T,teleportation_factor.T)
    if i<=100:
      return new_p
    i=i+1
    teleportation_factor = new_p
  
  
result_rank=text_rank(cosine_similarity_matrix)
print(len(word_list))
rank_with_sentence={}
for i in range(len(word_list)):
  if result_rank[i] not in set(rank_with_sentence.keys()):
    rank_with_sentence[result_rank[i]]=[word_list[i]]
  else:
    rank_with_sentence[result_rank[i]].append(word_list[i])
    

#sentences with their rank
for key in sorted(rank_with_sentence.keys(),reverse=True)[:int(len(rank_with_sentence.keys())/4)]:
  for k in rank_with_sentence[key]:
    #print(key,k)
#     k[0].upper()
    print(k)

154
system administrator must able change student detail
role right take document right document owns another role
system provides predefined report consumption library board consumer report providing basic statistic like required georgia annual report application state aid activity report indicate traffic volume use display statistic checkout checkins hold placed hold filled possible crosstabulated per terminal per branch per library system per hour per patron age range per patron type per patron location
role right create subordinate role
end user person role
client administrator view role
role right assign document right document owns another role
role right update subordinate role
user query cluster establish cost unit time submit job
user check usage pattern history cluster
user check status submit job
role update right update file document space associated role
system administrator create reliable report template available staff run modified staff person particular need change te

<h3>Konstruksi&nbsp;<strong>Word Embedding (skip-gram) -> ga dipake</strong></h3>


In [2]:
import pandas as pd
from gensim.models import Word2Vec

def tokenization(lemmatized_word):
    #tokenization
    from nltk.tokenize import word_tokenize
    tokens = word_tokenize(lemmatized_word)
    return tokens

news = pd.read_csv('dataprep1.csv', sep=',', encoding='latin-1')
newss=[]

for i in range(100):
    news['0'][i] = tokenization(news['0'][i])
    newss.append(news['0'][i])

C:\Users\asus\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [3]:
newss

[['user',
  'submit',
  'job',
  'associate',
  'deadline',
  'cost',
  'execution',
  'time'],
 ['user',
  'query',
  'cluster',
  'establish',
  'cost',
  'unit',
  'time',
  'submit',
  'job'],
 ['user', 'monitor', 'status', 'submit', 'job'],
 ['user', 'cancel', 'job', 'submit'],
 ['user', 'check', 'credit', 'balance'],
 ['user', 'check', 'usage', 'history'],
 ['user', 'check', 'status', 'node', 'cluster'],
 ['user', 'check', 'usage', 'pattern', 'history', 'cluster'],
 ['user', 'check', 'status', 'submit', 'job'],
 ['user', 'check', 'load', 'node', 'cluster'],
 ['user', 'alters', 'cost', 'structure', 'cluster'],
 ['user', 'alters', 'schedule', 'policy', 'cluster'],
 ['user', 'take', 'photo', 'new', 'student'],
 ['development',
  'process',
  'follow',
  'rational',
  'unified',
  'process',
  'rup',
  'approach'],
 ['sdms', 'developed', 'waterfall', 'process', 'model'],
 ['objective',
  'project',
  'develop',
  'meeting',
  'scheduler',
  'product',
  'organized',
  'routine',
  'a

In [169]:
model = Word2Vec(newss, min_count=1, sg=1)
# summarize the loaded model
print(model)

Word2Vec(vocab=307, size=100, alpha=0.025)


In [170]:
# summarize vocabulary
words = list(model.wv.vocab)
print(words)

['user', 'submit', 'job', 'associate', 'deadline', 'cost', 'execution', 'time', 'query', 'cluster', 'establish', 'unit', 'monitor', 'status', 'cancel', 'check', 'credit', 'balance', 'usage', 'history', 'node', 'pattern', 'load', 'alters', 'structure', 'schedule', 'policy', 'take', 'photo', 'new', 'student', 'development', 'process', 'follow', 'rational', 'unified', 'rup', 'approach', 'sdms', 'developed', 'waterfall', 'model', 'objective', 'project', 'develop', 'meeting', 'scheduler', 'product', 'organized', 'routine', 'allows', 'u', 'concentrate', 'core', 'element', 'different', 'phase', 'easily', 'efficiently', 'web', 'tier', 'deal', 'presentation', 'logic', 'page', 'rendering', 'eis', 'responsible', 'storing', 'profile', 'ride', 'advertisement', 'runtime', 'applied', 'done', 'extra', 'application', 'server', 'deployed', 'working', 'future', 'ibm', 'running', 'jboss', 'database', 'mysql', 'redundancy', 'using', 'mirroring', 'raid', 'mode', 'workstation', 'run', 'linux', 'use', 'eclips

In [171]:
# save model
model.save('modeln.bin')
# load model
new_model = Word2Vec.load('modeln.bin')
print(new_model)

Word2Vec(vocab=307, size=100, alpha=0.025)


In [172]:
from sklearn.feature_extraction.text import CountVectorizer

def get_top_n_words(corpus, n=None):
    vec = CountVectorizer(stop_words = stopwords.words('english')).fit(corpus)
    bag_of_words = vec.transform(corpus)
    sum_words = bag_of_words.sum(axis=0) 
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec.vocabulary_.items()]
    words_freq =sorted(words_freq, key = lambda x: x[1], reverse=True)
    return words_freq[:n]
common_words = get_top_n_words(word_list, 20)
for word, freq in common_words:
    print(word, freq)
df2 = pd.DataFrame(common_words, columns = ['News' , 'count'])

role 54
system 44
user 32
item 30
report 27
per 26
document 21
staff 20
right 19
patron 18
server 16
administrator 16
student 14
project 14
library 14
application 13
hold 13
ability 13
design 12
record 12


In [173]:
result3 = model.most_similar('user', topn=5)
print(result3)

[('system', 0.32030031085014343), ('rendering', 0.3131704330444336), ('balance', 0.27029669284820557), ('development', 0.24968262016773224), ('view', 0.24678455293178558)]


C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


In [182]:
new_isomodel = Word2Vec.load('isomodel.bin')
print(new_isomodel)

Word2Vec(vocab=41, size=100, alpha=0.025)


In [183]:
results = new_isomodel.most_similar('administration', topn=5)
print(results)

[('environment', 0.19473305344581604), ('alert', 0.09444408118724823), ('virus', 0.07332561910152435), ('tester', 0.06715662032365799), ('develop', 0.0669461265206337)]


C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.
